ARG version
FROM almalinux:${version}
RUN echo "The currernt version : ${version}"
# before mentioned ARG varialbes will not reflect after FROM command"

# after mentioned ARG variables will not reflect before FROM command

ARG course
RUN echo "The currernt course is: ${course}}"
