networks:
  roboshop:
    driver: bridge
services:
  mongodb: 
    image: mongodb:v1
    container_name: mongodb
    networks:
      - roboshop
  
  catalogue: 
    image: catalogue:v1
    container_name: catalogue
    networks:
      - roboshop
    depends_on:
      - mongodb

  redis:
    image: redis
    container_name: redis
    networks:
      - roboshop
    depends_on:
      - user
  user:
    image: user:v1
    container_name: user
    networks:
      - roboshop
    depends_on:
      - redis